---

stages:
  - test
  - document
  - publish

before_script:
  - python -m pip install -e .

.tests_template: &tests_definition
  stage: test
  script:
    - python -m pip install ipaddress six
    - python -m pip install -r requirements-tests.txt
    - git submodule init && git submodule update
    - py.test --cov jsonspec --cov-report term-missing tests/
  except:
    - docs

python2.7 tests:
  <<: *tests_definition
  tags:
    - python2.7

python3.4 tests:
  <<: *tests_definition
  tags:
    - python3.4

python3.5 tests:
  <<: *tests_definition
  tags:
    - python3.5

pages:
  stage: document
  script:
    - python -m pip install sphinx
    - python -m pip install -r docs/requirements.txt
    - sphinx-build -b html docs public
  artifacts:
    paths:
      - public
  only:
    - master
    - docs
  tags:
    - python3.5

publish to pypi:
  stage: publish
  script:
    - python -m pip install twine wheel
    - python setup.py sdist bdist_wheel
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  tags:
    - python3.5
  only:
    - /^v[\d\.]+.*$/
  allow_failure: true
