language: python
sudo: false
python:
  - pypy
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install -e .
  - pip install ipaddress six
  - pip install -r requirements-tests.txt
  - git submodule init && git submodule update

script:
  - py.test tests
